### ISSUE TITLE
adapters: Adjust to changes in LaxarJS

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-mocks#12]
Due to LaxarJS/laxar#221 the widget loader api was changed. Although this is actually a private API, it is used as a tooling interface by LaxarJS Testing. Hence this needs to be adapted there as well.
Marked as _breaking_, but since LaxarJS Testing is still a 0.x version, this is acceptable.

**Comment by x1B** [comment]
Fixed on `master` (`v0.4.0`).
