### ISSUE TITLE
Update spec runner to jasmine 2.4 and SystemJS usage

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-mocks#25]
Before we can safely start with any more transformation of ES5 code to ES2015 code, we need to update our test runners and tests.
Additionally we need to create some minimal boilerplate code (perhaps as a micro laxar dev library) to get rid of laxar-testing here.

**Comment by x1B** [comment]
I guess since we have moven to webpack in the meantime, this can be _closed_ as _wont fix_.
