### ISSUE TITLE
add widget feature schema validation

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-mocks#33]
Because the laxar widget loader no longer processes schema information from the widget.json, laxar-mocks needs to do schema processing by itself. It might use `laxar-tooling` as a dependency to avoid duplication.

**Comment by alex3683** [comment]
Just a quick note: Current test failure is caused by this.

(Just to put some pressure behind this  :smiling_imp:)

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
