### ISSUE TITLE
feature/documentation request: allow mocking widget services without a widget

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-mocks#50]
Some tests (laxar-uikit, various controls) need to mock widget services (for example i18n, configuration). Not only is it a pain to hand-code these mocks in every repository, it is also a source of error because changes in the API of the mocked services are hidden from the tests.

Is it currently possible to instantiate the mocks without a widget? If not: can we provide an API to do that easily, maybe by stubbing a minimal widget descriptor? If it is already possible, we should add documentation "somewhere" :)

**Comment by x1B** [comment]
@jpommerening Is using something like `import { createAxAssetsMock } from 'laxar/laxar-widget-service-mocks` good enough? This is what LaxarJS Mocks uses to obtain mocks. If so, I suggest closing this issue.

If using the mock factories is too tedious, maybe we need to raise a laxar issue instead.

**Comment by jpommerening** [comment]
TBH, I think the only problem seems to be that I have no idea how I'd create an i18n mock with any of that and was hoping `laxar-mocks` could do the job for me :)

`createAxI18nMock` needs an actual axI18n service, which (if I manage to get hold of its factory function) needs axConfiguration and axContext, which in turn, might look different with the serviceDecorators, once the control is actually used inside a widget. Maybe this is all misinformed, but that's why there's the `/documentation` in the title ;)

Here: https://github.com/LaxarJS/ax-input-control/blob/master/spec/helpers.js#L28 (careful; brittle)

**Comment by x1B** [comment]
Agreed, creating a mock for the axI18n injections should be simpler.
For v2.0, I'd suggest leaving the scope of laxar-mocks as-is (preconfigured testbed for _widgets_) and opening an _enhancement_ issue in laxar core instead, to make it dead-simple to obtain a working axI18n mock.

**Comment by jpommerening** [comment]
Ok, thanks!

**Comment by jpommerening** [comment]
Closing in favor of LaxarJS/laxar#447

**Comment by x1B** [comment]
@jpommerening thx 👍
